(function() {function Zap(){}var View=function(a,b,c){this.h=a;this.w=b;this.zap=c;this.wires=[];this.placements=[]};View.prototype.render=function(a){var b=a.append("svg").attr("width",this.w).attr("height",this.h);this.wires.forEach(function(a){console.log("wire",a);a.render(b)});this.placements.forEach(function(a){console.log("component",a);a.component.render(b)})};View.prototype.place=function(a,b,c){a.place(b,c);this.placements.push({component:a,x:b,y:c})};
Zap.prototype.createView=function(a,b){return new View(a,b,this)};window.Zap=Zap;function Component(){this.rotation=this.y=this.x=0}Component.prototype.rotateLeft=function(){this.rotation-=Math.PI/2;console.log("rotate left",this.rotation);this.calculateTerminals()};Component.prototype.rotateRight=function(){this.rotation+=Math.PI/2;this.calculateTerminals()};Component.prototype.flip=function(){this.rotation+=Math.PI;this.calculateTerminals()};Component.prototype.place=function(a,b){this.x=a;this.y=b;this.calculateTerminals()};
Component.prototype.renderText=function(){var a=this.rotation%(2*Math.PI),b=this.x,c=this.y;if(0==a)b+=20,c+=5;else if(a==Math.PI||a==-Math.PI)b-=50,c+=5;else if(a==-Math.PI/2||a==1.5*-Math.PI)b-=10,c-=25;else if(a==Math.PI/2||a==1.5*-Math.PI)b-=15,c+=35;return{x:b,y:c}};
Component.prototype.calculateTerminals=function(){var a=this.rotation%(2*Math.PI);console.log("actual rotation",a);if(0==a)console.log("0 rotation"),this.placeUp();else if(a==Math.PI||a==-Math.PI)console.log("down rotation"),this.placeDown();else if(a==-Math.PI/2||a==1.5*Math.PI)console.log("left rotation"),this.placeLeft();else if(a==Math.PI/2||a==1.5*-Math.PI)console.log("right rotation"),this.placeRight()};var Battery=function(a){this.voltage=a;this.in=new Connection(this);this.out=new Connection(this)};Battery.prototype=new Component;Battery.prototype.placeUp=function(){this.in.place(this.x,this.y-22.5);this.out.place(this.x,this.y+22.5)};Battery.prototype.placeDown=function(){this.in.place(this.x,this.y+22.5);this.out.place(this.x,this.y-22.5)};Battery.prototype.placeLeft=function(){this.in.place(this.x-22.5,this.y);this.out.place(this.x+22.5,this.y)};
Battery.prototype.placeRight=function(){this.in.place(this.x+22.5,this.y);this.out.place(this.x-22.5,this.y)};
Battery.prototype.render=function(a){var b=this;a.selectAll("div").data([10,15,30,15,30,15,30,10]).enter().append("svg:path").attr("d",function(a,c){return 0==c?"M "+b.x+" "+(b.y-22)+" l 0 "+a:7==c?"M "+b.x+" "+(b.y+12.5)+" l 0 "+a:"M "+(b.x+-7*((c-1)%2)-7.5)+" "+(b.y+5*(c-1)-12.5)+" l "+a+" 0"}).attr("transform","rotate("+180*(b.rotation/Math.PI)+" "+b.x+", "+b.y+")").attr("class","zap-line component");var c=this.renderText();a.append("text").attr("class","zap-label").attr("transform","translate("+
c.x+","+c.y+")").text(b.voltage+"V");return this};Zap.prototype.createBattery=function(a){return new Battery(a)};var Capacitor=function(a){this.capacitance=a;this.in=new Connection(this);this.out=new Connection(this)};Capacitor.prototype=new Component;Capacitor.prototype.placeUp=function(){this.in.place(this.x,this.y-17.5);this.out.place(this.x,this.y+17.5)};Capacitor.prototype.placeDown=function(){this.in.place(this.x,this.y+17.5);this.out.place(this.x,this.y-17.5)};Capacitor.prototype.placeLeft=function(){this.in.place(this.x-17.5,this.y);this.out.place(this.x+17.5,this.y)};
Capacitor.prototype.placeRight=function(){this.in.place(this.x+17.5,this.y);this.out.place(this.x-17.5,this.y)};
Capacitor.prototype.render=function(a){var b=this;a.selectAll("div").data([10,25,25,10]).enter().append("svg:path").attr("d",function(a,c){return 0==c?"M "+b.x+" "+(b.y-18)+" l 0 "+a:3==c?"M "+b.x+" "+(b.y+7.5)+" l 0 "+a:"M "+(b.x-12.5)+" "+(b.y+15*((c-1)%2)-7.5)+" l "+a+" 0"}).attr("transform","rotate("+180*(this.rotation/Math.PI)+" "+this.x+", "+this.y+")").attr("class","zap-line component");var c=this.renderText();a.append("text").attr("class","zap-label").attr("transform","translate("+c.x+","+
c.y+")").text(this.capacitance+"\u00b5F");return this};Zap.prototype.createCapacitor=function(a){return new Capacitor(a)};function Connection(a){this.base=a;this.y=this.x=0}Connection.prototype.place=function(a,b){this.x=a||0;this.y=b||0};var Ground=function(){this.in=new Connection(this)};Ground.prototype=new Component;Ground.prototype.placeUp=function(){this.in.place(this.x,this.y-17.5)};Ground.prototype.placeDown=function(){this.in.place(this.x,this.y+17.5)};Ground.prototype.placeLeft=function(){this.in.place(this.x-17.5,this.y)};Ground.prototype.placeRight=function(){this.in.place(this.x+17.5,this.y)};
Ground.prototype.render=function(a){var b=this;a.selectAll("div").data([10,30,20,10]).enter().append("svg:path").attr("d",function(a,d){return 0==d?"M "+b.x+" "+(b.y-15)+" l 0 "+a:"M "+(b.x+5*(d-1)-15)+" "+(b.y+5*(d-1)-5)+" l "+a+" 0"}).attr("transform","rotate("+180*(this.rotation/Math.PI)+" "+this.x+", "+this.y+")").attr("class","zap-line component");return this};Zap.prototype.createGround=function(){return new Ground(this)};var OpAmp=function(a){this.model=a;this.vPos=new Connection(this);this.vNeg=new Connection(this);this.vSPos=new Connection(this);this.vSNeg=new Connection(this);this.vOut=new Connection(this)};OpAmp.prototype=new Component;OpAmp.prototype.placeUp=function(){this.vPos.place(this.x-15*(1/3),this.y+9);this.vNeg.place(this.x+5,this.y+9);this.vSPos.place(this.x-7.5,this.y-3);this.vSNeg.place(this.x+7.5,this.y-3);this.vOut.place(this.x,this.y-9)};
OpAmp.prototype.placeDown=function(){this.vPos.place(this.x-15*(1/3),this.y-9);this.vNeg.place(this.x+5,this.y-9);this.vSPos.place(this.x-7.5,this.y+3);this.vSNeg.place(this.x+7.5,this.y+3);this.vOut.place(this.x,this.y+9)};OpAmp.prototype.placeLeft=function(){this.vPos.place(this.x+9,this.y-15*(1/3));this.vNeg.place(this.x+9,this.y+5);this.vSPos.place(this.x-3,this.y-7.5);this.vSNeg.place(this.x-3,this.y+7.5);this.vOut.place(this.x-9,this.y)};
OpAmp.prototype.placeRight=function(){this.vPos.place(this.x-9,this.y-15*(1/3));this.vNeg.place(this.x-9,this.y+5);this.vSPos.place(this.x+3,this.y-7.5);this.vSNeg.place(this.x+3,this.y+7.5);this.vOut.place(this.x+9,this.y)};
OpAmp.prototype.render=function(a){var b=this,c=[{x:15,y:-18},{x:15,y:18}];a.append("path").attr("d",function(){var a=" ";c.forEach(function(b){a+="l "+b.x+" "+b.y+" "});a+="z";return"M "+(b.x-15)+" "+(b.y+9)+a}).attr("transform","rotate("+180*(this.rotation/Math.PI)+" "+this.x+", "+this.y+")").attr("class","zap-line component");var d=this.renderText();a.append("text").attr("class","zap-label").attr("transform","translate("+d.x+","+d.y+")").text(this.model);return this};
Zap.prototype.createOpAmp=function(a){return new OpAmp(a)};var Resistor=function(a){this.resistance=a;this.in=new Connection(this);this.out=new Connection(this)};Resistor.prototype=new Component;Resistor.prototype.placeUp=function(){this.in.place(this.x,this.y-17.5);this.out.place(this.x,this.y+17.5)};Resistor.prototype.placeDown=function(){this.in.place(this.x,this.y+17.5);this.out.place(this.x,this.y-17.5)};Resistor.prototype.placeLeft=function(){this.in.place(this.x-17.5,this.y);this.out.place(this.x+17.5,this.y)};
Resistor.prototype.placeRight=function(){this.in.place(this.x+17.5,this.y);this.out.place(this.x-17.5,this.y)};
Resistor.prototype.render=function(a){var b=this,c=[{x:0,y:5},{x:-5,y:2.5},{x:10,y:5},{x:-10,y:5},{x:10,y:5},{x:-10,y:5},{x:5,y:2.5},{x:0,y:5}];a.append("svg:path").attr("d",function(){var a=" ";c.forEach(function(b){a+="l "+b.x+" "+b.y+" "});return"M "+b.x+" "+(b.y-17.5)+a}).attr("transform","rotate("+180*(b.rotation/Math.PI)+" "+b.x+", "+b.y+")").attr("class","zap-line component");var d=this.renderText();a.append("text").attr("class","zap-label").attr("transform","translate("+d.x+","+d.y+")").text(this.resistance+
"\u2126");return this};Zap.prototype.createResistor=function(a){return new Resistor(a)};var Wire=function(a,b){this.comp1=a;this.comp2=b;this.intersections=[]};
Wire.prototype.render=function(a){console.log("end",this.comp2.wire);var b={x:this.comp1.x,y:this.comp1.y},c={x:this.comp2.x,y:this.comp2.y};this.intersections.forEach(function(c){var e=c.x,f=c.y;a.append("svg:path").attr("d",function(){return"M "+b.x+" "+b.y+" l "+(e-b.x)+" "+(f-b.y)}).attr("class","zap-line component");b={x:e,y:f}});a.append("svg:path").attr("d",function(){console.log("wire path",b,c);return"M "+b.x+" "+b.y+" l "+(c.x-b.x)+" "+(c.y-b.y)}).attr("class","zap-line component");return this};
Wire.prototype.intersect=function(a,b){this.intersections.push({x:a,y:b})};Zap.prototype.connect=function(a,b){return new Wire(a,b)};})();
