(function() {function Zap(){}var View=function(a,b,c){this.h=a;this.w=b;this.zap=c;this.wires=[];this.placements=[]};View.prototype.render=function(a){var b=a.append("svg").attr("width",this.w).attr("height",this.h);this.wires.forEach(function(a){console.log("wire",a);a.render(b)});this.placements.forEach(function(a){console.log("component",a);a.component.render(b)})};View.prototype.place=function(a,b,c){a.place(b,c);this.placements.push({component:a,x:b,y:c})};
Zap.prototype.createView=function(a,b){return new View(a,b,this)};window.Zap=Zap;var Battery=function(a){this.voltage=a;this.in=new Connection(this);this.out=new Connection(this);this.y=this.x=this.rotation=0};
Battery.prototype.calculateTerminals=function(){var a=this.rotation%(2*Math.PI);if(0==a)this.in.place(this.x,this.y-12.5),this.out.place(this.x,this.y+12.5);else if(a==Math.PI||a==-Math.PI)this.in.place(this.x,this.y+12.5),this.out.place(this.x,this.y-12.5);else if(a==-Math.PI/2||a==1.5*-Math.PI)this.in.place(this.x-12.5,this.y),this.out.place(this.x+12.5,this.y);else if(a==Math.PI/2||a==1.5*-Math.PI)this.in.place(this.x+12.5,this.y),this.out.place(this.x-12.5,this.y);console.log("calculating",this.in,
this.out)};Battery.prototype.rotateLeft=function(){this.rotation-=Math.PI/2;this.calculateTerminals()};Battery.prototype.rotateRight=function(){this.rotation+=Math.PI/2;this.calculateTerminals()};Battery.prototype.flip=function(){this.rotation+=Math.PI;this.calculateTerminals()};Battery.prototype.place=function(a,b){this.x=a;this.y=b;this.calculateTerminals()};
Battery.prototype.render=function(a){var b=this;a.selectAll("div").data([15,30,15,30,15,30]).enter().append("svg:path").attr("d",function(a,c){return"M "+(b.x+-7*(c%2)-7.5)+" "+(b.y+5*c-12.5)+" l "+a+" 0"}).attr("transform","rotate("+180*(b.rotation/Math.PI)+" "+b.x+", "+b.y+")").attr("class","zap-line component");var c=b.rotation%(2*Math.PI),e=b.x,d=b.y;if(0==c)e+=20,d+=5;else if(c==Math.PI||c==-Math.PI)e-=50,d+=5;else if(c==-Math.PI/2||c==1.5*-Math.PI)e-=10,d-=25;else if(c==Math.PI/2||c==1.5*-Math.PI)e-=
15,d+=35;a.append("text").attr("class","zap-label").attr("transform","translate("+e+","+d+")").text(b.voltage+"V");return this};Zap.prototype.createBattery=function(a){return new Battery(a)};var Capacitor=function(a,b){this.capacitance=a;this.w=b.baseWidth;this.h=b.baseHeight};Capacitor.prototype.render=function(a){a=a.append("svg").attr("width",this.w).attr("height",this.h);a.selectAll("div").data([40,40]).enter().append("svg:path").attr("d",function(a,c){return"M "+(100+20*(c%2))+" 0 l 0 30"}).attr("class","zap-line component");a.append("text").attr("class","zap-label").attr("transform","translate(80,50)").text(this.capacitance+"F");return this};
Zap.prototype.createCapacitor=function(a){return new Capacitor(a,this)};function Connection(a){this.base=a;this.y=this.x=0}Connection.prototype.place=function(a,b){this.x=a||0;this.y=b||0};var Ground=function(a){this.w=a.baseWidth;this.h=a.baseHeight};Ground.prototype.render=function(a){a.append("svg").attr("width",this.w).attr("height",this.h).selectAll("div").data([30,20,10]).enter().append("svg:path").attr("d",function(a,c){return"M "+(100+5*c)+" "+(100+5*c)+" l "+a+" 0"}).attr("class","zap-line component");return this};Zap.prototype.createGround=function(){return new Ground(this)};var OpAmp=function(a,b){this.model=a;this.w=b.baseWidth;this.h=b.baseHeight};OpAmp.prototype.render=function(a){a=a.append("svg").attr("width",this.w).attr("height",this.h);a.append("path").attr("d",function(){return"M 100 100 l 40 25 l -40 25 z"}).attr("class","zap-line component");a.append("text").attr("class","zap-label").attr("transform","translate(120,130)").text(this.model);return this};Zap.prototype.createOpAmp=function(a){return new OpAmp(a,this)};var Resistor=function(a,b){this.resistance=a;this.w=b.baseWidth;this.h=b.baseHeight};Resistor.prototype.render=function(a){a=a.append("svg").attr("width",this.w).attr("height",this.h);a.append("svg:path").attr("d",function(){return"M 100 100 l 10 0 l 5 10 l 10 -20 l 10 20 l 10 -20 l 10 20 l 5 -10 l 10 0"}).attr("class","zap-line component");a.append("text").attr("class","zap-label").attr("transform","translate(120,130)").text(this.resistance+"\u2126");return this};
Zap.prototype.createResistor=function(a){return new Resistor(a,this)};var Wire=function(a,b){this.comp1=a;this.comp2=b;this.intersections=[]};
Wire.prototype.render=function(a){console.log("end",this.comp2.wire);var b={x:this.comp1.x,y:this.comp1.y},c={x:this.comp2.x,y:this.comp2.y};this.intersections.forEach(function(c){var d=c.x,f=c.y;a.append("svg:path").attr("d",function(){return"M "+b.x+" "+b.y+" l "+(d-b.x)+" "+(f-b.y)}).attr("class","zap-line component");b={x:d,y:f}});a.append("svg:path").attr("d",function(){console.log("wire path",b,c);return"M "+b.x+" "+b.y+" l "+(c.x-b.x)+" "+(c.y-b.y)}).attr("class","zap-line component");return this};
Wire.prototype.intersect=function(a,b){this.intersections.push({x:a,y:b})};Zap.prototype.connect=function(a,b){return new Wire(a,b)};})();
